---
title: "Rich-collab.Rmd"
author: "Stephanie & Rich"
date: "12/1/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

## CHUNKY MONKEY

## NYC Flight exploration
```{r}

library(nycflights13) # install.packages("nycflights13")

## Jan 1 flights

flights %>% 
  filter(month == 1,
         day == 1)


```

## Boolean fun

```{r}

library(tidyverse)

filter(flights, month == 11 | month == 12)

# The following will give the same result, %in% is a shortcut

nov_dec <- filter(flights, month %in% c(11, 12))

#The following two command lines will give you the flights that weren't delayed on arrival or departure by more than 2 hours

filter(flights, !(arr_delay > 120| dep_delay > 120))

#or

filter(flights, arr_delay <= 120, dep_delay <= 120)

```


